### PR TITLE
add a project into your repo

### PR DESCRIPTION
**Pull request by AlfatTaufik**
Hi im still learning to contribute into open source, if i made any mistake may  you tell me 
that will so meanfull for my learning path
If nothing wrong may you accept this PR 
Thank you

### CODE REVIEW

**Review by Sar-taj107 — APPROVED** [review]
Thanks for your contribution🎉 !

I noticed that your are actually add a project related to the dev or like a simple card , but is repo is dedicatedly made for implementation of DSA problem but as you mention you're exploring the open source then its fine i will merge this PR after go through once and check should it works properly or not.

if you like this repo pls do share with friends and give a star 🌟 to show your support it means a lot.

**Comment by AlfatTaufik** [comment]
I just can say thank you, but can i ask you something

Why on my hacktoberfest profile this PR is read by not accepted can you help me

**Comment by Sar-taj107** [comment]
sure @AlfatTaufik  let's check once again i think now it will showing that getting merged.
if you find so then pls give a star 🌟 to support & also motivate me to contributing continuously in open source.

thanks!

**Comment by AlfatTaufik** [comment]
Ah ya, now its accepted

Thanks a lot sir for your help, of course im gonna give all star for your help

Once again thanksyou so much its mean a lot for me 😁

**Comment by AlfatTaufik** [comment]
Can i send Another PR to your other Hacktoberfest repo?

**Comment by Sar-taj107** [comment]
yeah sure @AlfatTaufik why not always welcome dear!

**Pull request merged**
