### PR TITLE
Added algorithms with implementation in java

### PR DESCRIPTION
**Pull request by saty-a**
please add hacktoberfest label before merging
Thanks in advance

### CODE REVIEW

**Comment by Sar-taj107** [comment]
your file is empty please re-check and try again for PR
Satya-a

**Comment by saty-a** [comment]
> your file is empty please re-check and try again for PR Satya-a

I have updated the programs. Please merge this PR

**Comment by saty-a** [comment]
I have updated the PR please check!!

**Review by Sar-taj107 — APPROVED** [review]
Thanks for your contribution🎉!

Do share the repo with your friends and encourage them to contribute for #hactoberfest and give a star to this repo to show your support and don't forget to follow!

Happy hacking! ^^

**Pull request merged**
