### PR TITLE
Solution Leetcode problem 88.MergeSort Easy

### PR DESCRIPTION
**Pull request by ThanasisNov**
If you need more information about the problem , in a readme file tell me to add it .Thanks for your time!

### CODE REVIEW

**Review by Sar-taj107 — COMMENTED** [review]
Thanks for the contributions!🎉
if possible you can add readme.md file to explain the problem as well, it will be more helpful for us.

**Comment by ThanasisNov** [comment]
> Thanks for the contributions!🎉 if possible you can add readme.md file to explain the problem as well, it will be more helpful for us.

Of course , i will get back to you soon!

**Comment by ThanasisNov** [comment]
Hey! , i have done the Readme.md file about 88 problem and i have also added the problem to the main list in LeadCode Readme.md file, hope  that this is enought .Have a great day!

**Comment by ThanasisNov** [comment]
> Thanks for the contributions!🎉 if possible you can add readme.md file to explain the problem as well, it will be more helpful for us.

**Pull request closed without merging**
