### PR TITLE
new kotlin program

### PR DESCRIPTION
**Pull request by Sbiswas001**

### CODE REVIEW

**Comment by Sbiswas001** [comment]
added a new kotlin program

**Comment by Sbiswas001** [comment]
please accept this pr

**Comment by Sbiswas001** [comment]
please accept pull request

**Comment by Sar-taj107** [comment]
sorry for the delay can't see your PR before, fortunately today i see your mail regarding PR !

**Review by Sar-taj107 — COMMENTED** [review]
👍

**Pull request closed without merging**
