### PR TITLE
Doubly linked List prgrm added

### PR DESCRIPTION
**Pull request by Shreyasb1015**
This is doubly linked list implementation program written in c++ language.

### CODE REVIEW

**Review by Sar-taj107 — COMMENTED** [review]
Thanks for your contribution🎉!

I think you forget to add 'contributorfile.md' Please add the details in contributorList folder follow the instruction for fast review, and give a star ⭐ to this repo to show your support also for smooth review merge PR!

Do share the repo with your friends and encourage them to contribute for #hactoberfest
Happy hacking! ^^

**Comment by Shreyasb1015** [comment]
Now,I have created my contributer.md file. So,please merge my pr

**Review by Sar-taj107 — APPROVED** [review]
Thanks once again for contribution and followed the given instructions.
if you really like this repo please give a star 🌟 to support this and also it means alot for me.
& Yes, i will merge your PR soon!

H hacking^^

**Comment by Shreyasb1015** [comment]
Done! And Happy Hacking to you too!!

**Pull request merged**
