### PR TITLE
added array programs with C and C++

### PR DESCRIPTION
**Pull request by arpitbaheti2002**

### CODE REVIEW

**Review by Sar-taj107 — COMMENTED** [review]
Thanks for the contribution!

I've noticed that you're creating new folders unnecessarily. If the required folder already exists in the repo, please check for existing programs. There's no need to upload multiple & duplicate questions. Contribute the necessary content to maintain the quality of this repository.
so you just once go through the readme.md file there is all required info related to contribution & then upload your program in appropriate folder,  yes i will merge your PR!

**Comment by arpitbaheti2002** [comment]
Thank you for the feedback. I have moved the files to 01.Array directory. Please review my changes

**Review by Sar-taj107 — COMMENTED** [review]
Now its fine but again forget to add contributor.md file are you really go through the readme file, if not please once check it. 
its helps me to update the status of contributor for this repo. & also give a star to this repo to show your support!

thanks!

**Comment by arpitbaheti2002** [comment]
Extremely sorry, I missed that point. I have also starred the repository. Thank you for the opportunity.

**Review by Sar-taj107 — APPROVED** [review]

**Comment by Sar-taj107** [comment]
Now its completely fine once again Thanks for follow the instruction & your great contribution🎉🚀!

**Pull request merged**
