### PR TITLE
Create SumOfNaturalNumbers

### PR DESCRIPTION
**Pull request by pawarspeaks**

### CODE REVIEW

**Comment by pawarspeaks** [comment]
@Sar-taj107 kindly merge with a Hacktoberfest label. Thank you

**Review by Sar-taj107 — COMMENTED** [review]
Is this program run properly I noticed that there is no any extension  in your file. Please modify it and also add contributor list file. 
Thanks follow the readme.md file for quick merge PR! Give a star⭐ to this repo to show your support!

**Comment by pawarspeaks** [comment]
@Sar-taj107 done, kindly merge

**Comment by Sar-taj107** [comment]
please give a star 🌟 to this repo it also motivate me to continuously contributing in open source!

**Pull request merged**
